### ISSUE TITLE
Опечатка в HW1 №2.3

### ISSUE THREAD

**Issue by matrosik17** [amkatrutsa/nla2019_ozon#1]
Опечатка в разделе **2.3 Блочное LU разложение**.

![Screenshot_20191007_162651](https://user-images.githubusercontent.com/20338798/66316167-d2b75900-e91f-11e9-9ae9-f9fbcc06f856.png)

**Comment by amkatrutsa** [comment]
Это не опечатка, это кривое отображение на GitHub'e. Лучше смотрите с помощью [Nbviewer'a](https://nbviewer.jupyter.org/) (например, этот файл отображается [так](https://nbviewer.jupyter.org/github/amkatrutsa/nla2019_ozon/blob/master/hw/hw1/hw1.ipynb))
